"""make user columns not null

Revision ID: 0dbfe373e06d
Revises: 0beb1ed9a223
Create Date: 2020-05-02 16:03:27.762750

Copyright © retnikt <_@retnikt.uk> 2020
This software is licensed under the MIT Licence: https://opensource.org/licenses/MIT
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0dbfe373e06d"
down_revision = "0beb1ed9a223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
