"""add JTI table for token reuse prevention

Revision ID: b9381a474527
Revises: f2282c980d8e
Create Date: 2020-05-29 19:36:56.358459

Copyright (C) retnikt <_@retnikt.uk> 2020
This software is licensed under the MIT Licence: https://opensource.org/licenses/MIT
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b9381a474527"
down_revision = "f2282c980d8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jtis",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("expiry", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("jti"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jtis")
    # ### end Alembic commands ###
